### ISSUE TITLE
cannot play

### ISSUE THREAD

**Issue by leslie97** [RSATom/rtsp-test-server#1]
Hi!
I cannot play online demo URLs.
Please check it.
Thanks.

**Comment by RSATom** [comment]
Used hosting is too cheap to be stable... I'll restart it...

**Comment by RSATom** [comment]
vps restarted. It should work now.

**Comment by leslie97** [comment]
> 

Thank you so much.

**Comment by RSATom** [comment]
I would recommend you not rely too much on that server. It can go down at any moment...
You can just start you own server with https://snapcraft.io/rtsp-test-server even on Raspberry Pi
