### ISSUE TITLE
Using a prescribed port instead of 8554

### ISSUE THREAD

**Issue by helarsen** [RSATom/rtsp-test-server#2]
Are there a way to install rtsp-test-server such that it uses another port but 8554? 
If not - such a feature would be useful. 8554 clashes with other streams I have.
Thanks

**Comment by RSATom** [comment]
There is no any config support at the moment. I'll add...

**Comment by helarsen** [comment]
Great - I look forward to this update.

**Comment by RSATom** [comment]
@helarsen please try the latest version from `edge` channel

**Comment by RSATom** [comment]
Closing as implemented and published as snap to `stable` channel
